# Generated by Django 2.2.7 on 2019-11-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='año',
            field=models.CharField(default='2019', max_length=400),
        ),
    ]
