# Generated by Django 2.2.7 on 2019-11-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_dron_autonomia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dron',
            name='modelo',
            field=models.CharField(default='', max_length=400),
        ),
    ]
