# Generated by Django 2.2.7 on 2019-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_dron_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='costo',
            field=models.CharField(default='', max_length=400),
        ),
    ]
