# Generated by Django 2.2.7 on 2019-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0007_dron_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camara',
            old_name='año1',
            new_name='Calidad',
        ),
        migrations.RenameField(
            model_name='camara',
            old_name='modelo1',
            new_name='Sensor',
        ),
        migrations.AddField(
            model_name='camara',
            name='Objetivo',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='camara',
            name='Rango_ISO',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='camara',
            name='Resolucion',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='camara',
            name='Velocidad_obturacion',
            field=models.CharField(default='', max_length=400),
        ),
    ]
