# Generated by Django 2.2.7 on 2019-11-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0008_auto_20191123_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='tipo',
            field=models.CharField(choices=[('F', 'Ala Fija'), ('R', 'Ala Rotatoria')], default='', max_length=400),
        ),
    ]
