# Generated by Django 2.2.7 on 2019-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0010_auto_20191123_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dron',
            name='año',
        ),
        migrations.AddField(
            model_name='dron',
            name='camara_dron',
            field=models.CharField(choices=[('I', 'INCLUIDA'), ('NI', 'NO INCLUIDA')], default='', max_length=400),
        ),
        migrations.AddField(
            model_name='dron',
            name='tipo_motor',
            field=models.CharField(choices=[('E', 'ELECTRICO'), ('M', 'COMBUSTIÓN')], default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='dron',
            name='Tipo_de_dron',
            field=models.CharField(choices=[('F', 'Ala Fija'), ('R', 'Ala Rotatoria')], default='----', max_length=400),
        ),
    ]
