# Generated by Django 2.2.7 on 2019-11-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0011_auto_20191123_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='dron',
            name='numero_motores',
            field=models.CharField(default='', max_length=400),
        ),
    ]
